version: '3.1'

services:
  mariadb:
    image: mariadb:10
    restart: always
    container_name: mariadb
    command:
      - --innodb-strict-mode=OFF
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    command:
      - --innodb-strict-mode=OFF
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  mysql8:
    image: mysql:8
    restart: always
    container_name: mysql8
    command:
      - --innodb-strict-mode=OFF
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - ./mysql8/data:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3
    restart: always
    container_name: rabbitmq
    ports:
      - "5672:5672"
  redis:
    image: redis:7
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - UPLOAD_LIMIT=2048M
      - PMA_HOSTS=mysql,mysql8,mariadb
    links:
      - mysql
      - mysql8
      - mariadb